const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Text.Acts.SetY,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.loadingprogress
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Help: 0},
	{Active: 0},
	{Tween: 0},
	{btn_Hint: 0},
	{Mouse: 0},
	{Touch: 0},
	{Keyboard: 0},
	{btn_Close: 0},
	{btn_Menu: 0},
	{Buttons: 0},
	{Type: 0},
	{Destination: 0},
	{Notify: 0},
	{Notification: 0},
	{Pin: 0},
	{Heading: 0},
	{Text: 0},
	{Audio: 0},
	{Status: 0},
	{btn_noti_Down: 0},
	{btn_noti_Close: 0},
	{Exec: 0},
	{Transition: 0},
	{Clickme: 0},
	{Group: 0},
	{Button_11: 0},
	{Button_21: 0},
	{Button_22: 0},
	{Button_31: 0},
	{Button_32: 0},
	{Button_33: 0},
	{BG: 0},
	{Text_11: 0},
	{Logo: 0},
	{Loading_Bar: 0},
	{UI_Buttons: 0},
	{Clickables: 0},
	{Pin2: 0},
	{One_Button: 0},
	{Two_Buttons: 0},
	{Three_Buttons: 0},
	{Pressed_Button: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Help: class extends self.ISpriteInstance {},
	btn_Hint: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	btn_Close: class extends self.ISpriteInstance {},
	btn_Menu: class extends self.ISpriteInstance {},
	Notification: class extends self.ISpriteInstance {},
	Heading: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	btn_noti_Down: class extends self.ISpriteInstance {},
	btn_noti_Close: class extends self.ISpriteInstance {},
	Transition: class extends self.ISpriteInstance {},
	Clickme: class extends self.ISpriteInstance {},
	Button_11: class extends self.ISpriteInstance {},
	Button_21: class extends self.ISpriteInstance {},
	Button_22: class extends self.ISpriteInstance {},
	Button_31: class extends self.ISpriteInstance {},
	Button_32: class extends self.ISpriteInstance {},
	Button_33: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Text_11: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Loading_Bar: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	UI_Buttons: class extends self.ISpriteInstance {},
	Clickables: class extends self.ISpriteInstance {},
	One_Button: class extends self.ISpriteInstance {},
	Two_Buttons: class extends self.ISpriteInstance {},
	Three_Buttons: class extends self.ISpriteInstance {}
}