const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Dictionary,
		C3.Plugins.TextBox,
		C3.Behaviors.Fade,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.LockOrientation,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Text.Acts.SetY,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.SetVolume,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetOpacity,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.TextBox.Acts.SetY,
		C3.Plugins.TextBox.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.TextBox.Acts.SetBlur,
		C3.Plugins.TextBox.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.PolyPointXAt,
		C3.Plugins.Sprite.Exps.PolyPointYAt,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Help: 0},
	{Active: 0},
	{Tween: 0},
	{btn_Hint: 0},
	{Mouse: 0},
	{Touch: 0},
	{Keyboard: 0},
	{btn_Close: 0},
	{btn_Menu: 0},
	{Buttons: 0},
	{Type: 0},
	{Destination: 0},
	{Notify: 0},
	{Closed: 0},
	{Notification: 0},
	{Pin: 0},
	{Heading: 0},
	{Text: 0},
	{Audio: 0},
	{Status: 0},
	{btn_noti_Down: 0},
	{btn_noti_Close: 0},
	{Exec: 0},
	{Transition: 0},
	{btn_Location: 0},
	{Clickme: 0},
	{Group: 0},
	{Button_11: 0},
	{Button_21: 0},
	{Button_22: 0},
	{Button_31: 0},
	{Button_32: 0},
	{Button_33: 0},
	{BG: 0},
	{ID: 0},
	{btn_text: 0},
	{Logo: 0},
	{Loading_Bar: 0},
	{OD_Envelope: 0},
	{OD_Card: 0},
	{OD_Letter: 0},
	{OD_Ticket: 0},
	{Video: 0},
	{Envelope: 0},
	{Card: 0},
	{DragDrop: 0},
	{Letter: 0},
	{Ticket: 0},
	{Outside: 0},
	{Fade: 0},
	{all_text: 0},
	{TextInput: 0},
	{Puzzle_BG: 0},
	{Puzzle_Q_text: 0},
	{btn_Submit: 0},
	{Puzzle_text_BG: 0},
	{btn_submit_text: 0},
	{Phone: 0},
	{Cipher: 0},
	{Cipher_Hand: 0},
	{Photos: 0},
	{btn_Book_left: 0},
	{btn_Book_right: 0},
	{btn_Photos_left: 0},
	{btn_Photos_right: 0},
	{Book: 0},
	{Map_Marks: 0},
	{btn_CB: 0},
	{btn_CX: 0},
	{btn_KM: 0},
	{btn_JC: 0},
	{btn_NS: 0},
	{btn_TS: 0},
	{Secret_Code: 0},
	{btn_Continue: 0},
	{btn_RTH: 0},
	{BG_Fader: 0},
	{Attic: 0},
	{Use: 0},
	{MoveTo: 0},
	{Light: 0},
	{GO_Screen: 0},
	{btn_GO: 0},
	{ThankYou: 0},
	{UI_Buttons: 0},
	{Pin2: 0},
	{One_Button: 0},
	{Two_Buttons: 0},
	{Three_Buttons: 0},
	{Items: 0},
	{Puzzle: 0},
	{Notification_F: 0},
	{MAP_Buttons: 0},
	{Code_Panel: 0},
	{Fade2: 0},
	{GO: 0},
	{Pressed_Button: 0},
	{Disable_Hint: 0},
	{Animate_Hint: 0},
	{Allow_Click: 0},
	{Transition_Delay: 0},
	{Popup_Delay: 0},
	{Wait_for_notification: 0},
	{Wait_Gap: 0},
	{Knock: 0},
	{Apt_Desk_Notification: 0},
	{Hotel_Notification: 0},
	{BGM_Layout: 0},
	{BGM_Overlay: 0},
	{BGM_Fade: 0},
	{Loop1_Vol_Fader: 0},
	{BGM_Volume: 0},
	{Audio_Delay: 0},
	{Hotel_Window: 0},
	{Hotel_Desk_Notification: 0},
	{Hotel_Desk_BG: 0},
	{Read_Book: 0},
	{Show_puzzle: 0},
	{Puzzle_Solved: 0},
	{Puzzle_WIP: 0},
	{Phone_Msg_Popup: 0},
	{Look_Chiper: 0},
	{Look_Photos: 0},
	{Level_Progress: 0},
	{Map_Notification: 0},
	{Map_Selection: 0},
	{Puzzle_Direct: 0},
	{Next_Level: 0},
	{Level_BG: 0},
	{Orloj_BG: 0},
	{Orloj_Msg: 0},
	{Second_Hint: 0},
	{Rub_Feet: 0},
	{Click_Counter: 0},
	{Member: 0},
	{Player_Email: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Help: class extends self.ISpriteInstance {},
	btn_Hint: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	btn_Close: class extends self.ISpriteInstance {},
	btn_Menu: class extends self.ISpriteInstance {},
	Notification: class extends self.ISpriteInstance {},
	Heading: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	btn_noti_Down: class extends self.ISpriteInstance {},
	btn_noti_Close: class extends self.ISpriteInstance {},
	Transition: class extends self.ISpriteInstance {},
	Clickme: class extends self.ISpriteInstance {},
	Button_11: class extends self.ISpriteInstance {},
	Button_21: class extends self.ISpriteInstance {},
	Button_22: class extends self.ISpriteInstance {},
	Button_31: class extends self.ISpriteInstance {},
	Button_32: class extends self.ISpriteInstance {},
	Button_33: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	btn_text: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Loading_Bar: class extends self.ISpriteInstance {},
	OD_Envelope: class extends self.ISpriteInstance {},
	OD_Card: class extends self.ISpriteInstance {},
	OD_Letter: class extends self.ISpriteInstance {},
	OD_Ticket: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Envelope: class extends self.ISpriteInstance {},
	Card: class extends self.ISpriteInstance {},
	Letter: class extends self.ISpriteInstance {},
	Ticket: class extends self.ISpriteInstance {},
	Outside: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	all_text: class extends self.IDictionaryInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Puzzle_BG: class extends self.ISpriteInstance {},
	Puzzle_Q_text: class extends self.ISpriteInstance {},
	btn_Submit: class extends self.ISpriteInstance {},
	Puzzle_text_BG: class extends self.ISpriteInstance {},
	btn_submit_text: class extends self.ISpriteInstance {},
	Phone: class extends self.ISpriteInstance {},
	Cipher: class extends self.ISpriteInstance {},
	Cipher_Hand: class extends self.ISpriteInstance {},
	Photos: class extends self.ISpriteInstance {},
	btn_Book_left: class extends self.ISpriteInstance {},
	btn_Book_right: class extends self.ISpriteInstance {},
	btn_Photos_left: class extends self.ISpriteInstance {},
	btn_Photos_right: class extends self.ISpriteInstance {},
	Book: class extends self.ISpriteInstance {},
	Map_Marks: class extends self.ISpriteInstance {},
	btn_CB: class extends self.ISpriteInstance {},
	btn_CX: class extends self.ISpriteInstance {},
	btn_KM: class extends self.ISpriteInstance {},
	btn_JC: class extends self.ISpriteInstance {},
	btn_NS: class extends self.ISpriteInstance {},
	btn_TS: class extends self.ISpriteInstance {},
	Secret_Code: class extends self.ISpriteInstance {},
	btn_Continue: class extends self.ISpriteInstance {},
	btn_RTH: class extends self.ISpriteInstance {},
	BG_Fader: class extends self.ISpriteInstance {},
	Attic: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	GO_Screen: class extends self.ISpriteInstance {},
	btn_GO: class extends self.ISpriteInstance {},
	ThankYou: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	UI_Buttons: class extends self.ISpriteInstance {},
	One_Button: class extends self.ISpriteInstance {},
	Two_Buttons: class extends self.ISpriteInstance {},
	Three_Buttons: class extends self.ISpriteInstance {},
	Items: class extends self.ISpriteInstance {},
	Puzzle: class extends self.ISpriteInstance {},
	Notification_F: class extends self.ISpriteInstance {},
	MAP_Buttons: class extends self.ISpriteInstance {},
	Code_Panel: class extends self.ISpriteInstance {},
	GO: class extends self.ISpriteInstance {}
}